[package]
name = "discrete_optimization"
version = "0.1.0"
authors = ["Marcin Fatyga <fatygamarcin@gmail.com>"]
license = "Apache-2.0"

[dependencies]
rand = "0.3"
text_io = "0.1.5"
ndarray = "0.6.9"
simplesvg = "0.4.0"
itertools = "0.5.6"
getopts = "0.2"

[profile.release]
debug = false
